niccokunzmann/mundraub-android

app/src/main/AndroidManifest.xml, app/src/main/java/eu/quelltext/mundraub/activities/LoginActivity.java, app/src/main/java/eu/quelltext/mundraub/activities/MundraubBaseActivity.java, app/src/main/java/eu/quelltext/mundraub/activities/MundraubRulesActivity.java, app/src/main/java/eu/quelltext/mundraub/api/API.java, app/src/main/java/eu/quelltext/mundraub/api/DummyAPI.java, app/src/main/java/eu/quelltext/mundraub/api/MundraubAPI.java, app/src/main/java/eu/quelltext/mundraub/api/NaOvoceAPI.java, app/src/main/java/eu/quelltext/mundraub/map/PlantsCache.java, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_mundraub_rules.xml, app/src/main/res/menu/menu_app.xml, app/src/main/res/values/strings.xml
create sign-up process for Mundraub
- fixes #85
- requires #28
=> Mundraub signup

app/src/main/assets/map/examples/style.css, app/src/main/assets/map/theme/default/style.css, app/src/main/java/eu/quelltext/mundraub/activities/MundraubBaseActivity.java, app/src/main/java/eu/quelltext/mundraub/activities/NewPlantActivity.java, app/src/main/java/eu/quelltext/mundraub/activities/SettingsActivity.java, app/src/main/java/eu/quelltext/mundraub/api/MundraubAPI.java, app/src/main/java/eu/quelltext/mundraub/api/NaOvoceAPI.java, app/src/main/java/eu/quelltext/mundraub/common/Helper.java, app/src/main/java/eu/quelltext/mundraub/common/Settings.java, app/src/main/java/eu/quelltext/mundraub/error/Logger.java, app/src/main/java/eu/quelltext/mundraub/initialization/FruitRadarNotification.java, app/src/main/java/eu/quelltext/mundraub/initialization/Initialization.java, app/src/main/java/eu/quelltext/mundraub/map/PlantsCache.java, app/src/main/java/eu/quelltext/mundraub/plant/PlantCategory.java, app/src/main/res/layout/activity_settings.xml, app/src/main/res/values/strings.xml
=> Pr fruit radar

.travis.yml, app/src/main/java/eu/quelltext/mundraub/common/Helper.java, app/src/main/java/eu/quelltext/mundraub/initialization/FruitRadarNotification.java, app/src/main/res/values/strings.xml, app/src/test/java/eu/quelltext/mundraub/HelperPositionTest.java
=> Show the direction of the plant in notification

app/src/main/assets/map/request.js, app/src/main/java/eu/quelltext/mundraub/common/Helper.java, app/src/main/java/eu/quelltext/mundraub/initialization/FruitRadarNotification.java, app/src/main/java/eu/quelltext/mundraub/map/OfflinePlantsMapAPI.java, app/src/main/java/eu/quelltext/mundraub/map/PlantsCache.java, app/src/main/java/eu/quelltext/mundraub/map/position/BoundingBox.java, app/src/main/java/eu/quelltext/mundraub/map/position/IPosition.java, app/src/main/java/eu/quelltext/mundraub/map/position/Position.java, app/src/main/java/eu/quelltext/mundraub/map/position/RadiusBoundingBox.java, app/src/test/java/eu/quelltext/mundraub/BoundingBoxInclusionTest.java
- add a SENW bounding box and a radius bounding box
- refactor position parameters in map request.js
- create position interface
- get sql statement from bounding box
- contributes to https://github.com/niccokunzmann/mundraub-android/issues/111
=> contribute to taking the map offline

.travis/create_release, app/src/main/java/eu/quelltext/mundraub/activities/PlantListActivity.java
Hi, I removed 0x from listing.
For [#105](https://github.com/niccokunzmann/mundraub-android/issues/105)
=> Remove 0x from listing 

app/src/main/assets/map/examples/style.css, app/src/main/assets/map/theme/default/style.css
Problem: Incosistency between add plant button and map cotrols
Solution: Changing selected background values in style.css files
- [CSS] Use app colors for the map controls #197
- bug fix
@niccokunzmann, could you please review changes and accept pull request?
Thanks,
Robkoro
=> Changing map conrols from dark blue to app color (yellow)

app/src/main/java/eu/quelltext/mundraub/activities/NewPlantActivity.java, app/src/main/java/eu/quelltext/mundraub/plant/Plant.java
Refactored solution for master branch
-fix #34
=> Remove plant if it has default entries - master

app/src/main/java/eu/quelltext/mundraub/activities/SettingsActivity.java
I add notification with progress bar. I hope this time it will be OK.
=> notification

CONTRIBUTING.md, docs/setup.md
Problem: writing in setup.md could be improved
Line 3: removed ambiguity
Line 8-9: improved sentence structure
Line 11-12: increased brevity
Line 16: removed ambiguity of "it"
Line 17: removed pronoun 
Line 23: removed redundancy
Line 25: fixed grammar issues
Line 30-31: improved clarity
Line 34: removed pronoun
Line 36: removed pronoun
Line 59: improved sentence structure
Fixes #228 
Problem: grammar issues in CONTRIBUTING.md
Fixes #227
=> Fix Grammar and Redundancy in setup.md

CHANGELOG.json, app/src/main/assets/changelog/changelog.js, app/src/main/assets/changelog/cookie.js, app/src/main/assets/changelog/style.css, app/src/main/java/eu/quelltext/mundraub/activities/WebViewBaseActivity.java, scripts/changelog.html, scripts/generate-changelog.py
fixes https://github.com/niccokunzmann/mundraub-android/issues/240
=> make visible what changes since last version

CHANGELOG.json, app/src/main/assets/map/configuration.js, app/src/main/java/eu/quelltext/mundraub/activities/map/MapBaseActivity.java, app/src/main/java/eu/quelltext/mundraub/map/MapUrl.java, app/src/main/java/eu/quelltext/mundraub/map/position/BoundingBox.java, app/src/main/java/eu/quelltext/mundraub/search/AddressSearchResult.java, app/src/test/java/eu/quelltext/mundraub/AddressSearchResultTest.java, app/src/test/java/eu/quelltext/mundraub/MapUrlTest.java
=> Zoom map on search

app/src/main/java/eu/quelltext/mundraub/activities/map/MapBaseActivity.java, app/src/main/java/eu/quelltext/mundraub/activities/map/SelectOfflineMapPartsActivity.java
=> Use search in offline area view

CHANGELOG.json, app/src/main/java/eu/quelltext/mundraub/activities/SettingsActivity.java, app/src/main/java/eu/quelltext/mundraub/activities/map/TestFruitRadarActivity.java, app/src/main/java/eu/quelltext/mundraub/api/progress/Progressable.java, app/src/main/java/eu/quelltext/mundraub/api/progress/ProgressableResult.java, app/src/main/java/eu/quelltext/mundraub/initialization/Initialization.java, app/src/main/java/eu/quelltext/mundraub/notification/FruitRadarNotification.java, app/src/main/java/eu/quelltext/mundraub/notification/NotificationIDs.java, app/src/main/java/eu/quelltext/mundraub/notification/ProgressNotification.java, app/src/main/res/values/strings.xml
- refactor download notification into own class
- create notifications package
- create IDs for notifications centrally
- fixes https://github.com/niccokunzmann/mundraub-android/issues/147
=> add notifications for download of markers and map

CHANGELOG.json, README.md, app/src/main/java/eu/quelltext/mundraub/activities/SettingsActivity.java, app/src/main/java/eu/quelltext/mundraub/api/API.java, app/src/main/java/eu/quelltext/mundraub/api/CustomNaOvoceAPI.java, app/src/main/java/eu/quelltext/mundraub/api/CustomNaOvoceLoginAPI.java, app/src/main/java/eu/quelltext/mundraub/api/NaOvoceAPI.java, app/src/main/java/eu/quelltext/mundraub/common/Settings.java, app/src/main/java/eu/quelltext/mundraub/map/MapUrl.java, app/src/main/java/eu/quelltext/mundraub/map/PlantsCache.java, app/src/main/java/eu/quelltext/mundraub/plant/PlantCategory.java, app/src/main/java/eu/quelltext/mundraub/plant/PlantOnlineState.java, app/src/main/res/layout/activity_settings.xml, app/src/main/res/values/strings.xml
This adds the download of plants from custom servers, see #269
=> Na ovoce download

.travis.yml, app/build.gradle, app/src/main/java/eu/quelltext/mundraub/activities/NewPlantActivity.java, app/src/main/java/eu/quelltext/mundraub/common/Settings.java, app/src/main/java/eu/quelltext/mundraub/map/MundraubMapAPIForApp.java, app/src/test/java/eu/quelltext/mundraub/BoundingBoxTest.java, app/src/test/java/eu/quelltext/mundraub/PlantTest.java, app/src/test/java/eu/quelltext/mundraub/SynchronizedSetTest.java, app/src/test/java/eu/quelltext/mundraub/activities/NewPlantActivityTest.java, scripts/fetch-contrinutor
These are improvements from the community.
https://github.com/niccokunzmann/mundraub-android/network
=> Improvements from the community

.idea/misc.xml, app/build.gradle, app/src/androidTest/java/eu/quelltext/mundraub/espresso/unittest/AboutActivityTest.java, app/src/androidTest/java/eu/quelltext/mundraub/espresso/unittest/ChoosePlantTypeTest.java, app/src/androidTest/java/eu/quelltext/mundraub/espresso/unittest/CodexActivityTest.java, app/src/androidTest/java/eu/quelltext/mundraub/espresso/unittest/SettingActivityTest.java
This is a new pull request for #282.
=> Tests from #282

app/src/test/java/eu/quelltext/mundraub/HelperPositionTest.java, app/src/test/java/eu/quelltext/mundraub/common/HelperTest.java, app/src/test/java/eu/quelltext/mundraub/map/position/BoundingBoxTest.java, scripts/fetch-contrinutor
- https://github.com/niccokunzmann/mundraub-android/compare/master...Renefedorcak:master#diff-69bcb6686e1f4132caa1be9662858e00
- for https://github.com/niccokunzmann/mundraub-android/issues/283
=> add Helper tests

CHANGELOG.json, app/src/main/assets/map/examples/fullScreen.js, app/src/main/assets/map/examples/style.css, app/src/main/assets/map/icons.js, app/src/main/assets/map/plants.js, app/src/main/assets/map/request.js, app/src/main/assets/map/translations/en.js, app/src/main/java/eu/quelltext/mundraub/activities/LoginActivity.java, app/src/main/java/eu/quelltext/mundraub/activities/WebViewBaseActivity.java, app/src/main/java/eu/quelltext/mundraub/map/MundraubMapAPI.java, app/src/main/java/eu/quelltext/mundraub/map/MundraubMapAPIForApp.java, app/src/main/java/eu/quelltext/mundraub/map/handler/ErrorHandler.java, app/src/main/java/eu/quelltext/mundraub/map/handler/MockPlantCollectionHandler.java, app/src/main/java/eu/quelltext/mundraub/map/handler/PlantCollectionHandler.java, app/src/main/java/eu/quelltext/mundraub/map/handler/TilesHandler.java, app/src/main/java/eu/quelltext/mundraub/map/handler/URIHandler.java, app/src/main/java/eu/quelltext/mundraub/plant/Plant.java
- create handler package
- add handler for own plants
- fixes https://github.com/niccokunzmann/mundraub-android/issues/81 based on idea1
=> show own plants on map

.gitignore, app/src/main/gen/eu/quelltext/mundraub/BuildConfig.java, app/src/main/gen/eu/quelltext/mundraub/Manifest.java, app/src/main/gen/eu/quelltext/mundraub/R.java
fixes https://github.com/niccokunzmann/mundraub-android/issues/302
=> Clean up source code

app/src/main/res/values-it/strings.xml
Italian translation for strings.xml file
Co-Authored-By: fran-gian <104496968+fran-gian@users.noreply.github.com>
=> strings.xml (IT)
